### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [serapath/gofree#1]
## `@todo`
* [ ] [`gofree#2` PCBs](https://github.com/serapath/gofree/issues/2)
* [ ] [`gofree#3` 3D case model](https://github.com/serapath/gofree/issues/3)
* [ ] [`gofree#4` keyboard layout](https://github.com/serapath/gofree/issues/4)
* [ ] [`gofree#8` key switches](https://github.com/serapath/gofree/issues/8)
* [ ] [`gofree#5` BLE 5 & USB-C](https://github.com/serapath/gofree/issues/5)
* [ ] [`gofree#6` Trackball](https://github.com/serapath/gofree/issues/6)
* [ ] [`gofree#7` device software](https://github.com/serapath/gofree/issues/7)
* [ ] [`gofree#9` attach device to hand (e.g. glove)](https://github.com/serapath/gofree/issues/9)
* [ ] [`gofree#14` keycaps](https://github.com/serapath/gofree/issues/14)
* [ ] [`gofree#12` landingpage](https://github.com/serapath/gofree/issues/12)
* [ ] [`gofree#16` electronics "brain" (e.g. arduino)](https://github.com/serapath/gofree/issues/16)

---
**Wearable Wireless Split (QWERTY) Keyboard Glove with integrated Trackball (BLE 5, USB-C)**
