### ISSUE TITLE
rigid flex PCB

### ISSUE THREAD

**Issue by serapath** [serapath/gofree#10]
## `@todo`
* [ ] evaluate conductive PLA for 3D printing to wire up all single switch PCBs
  * https://www.proto-pasta.com/pages/conductive-pla#CCcoductivity
  * https://www.proto-pasta.com/products/conductive-pla
* [ ] make rigid flex PCB with KiCAD
* [ ] select a vendor and develop a [`flex PCB`][1] to connect the amoeba single switch PCBs

---
**inspire**
* http://www.4fpcb.com/flexible-circuitss/12-Layer-Rigid-Flex-PCB-with-Heat-Sink.html
* https://www.flexiblecircuit.com/product-category/rigid-flex/
* [flexpcb with crimp](https://my.mech.utah.edu/~wil/tutorials/flexCirc_soldering_tutorial/Flex_circuit_Soldering_Tutorial.html)

**inspire (layout)**
* https://i.imgur.com/YIt4n6W.jpg
* 

[1]: https://www.google.com/search?q=flex+pcb&source=lnms&tbm=isch&sa=X&ved=2ahUKEwizisqQiM3nAhXMJTQIHZHsBcoQ_AUoAXoECA0QAw&biw=1920&bih=939
