### ISSUE TITLE
PCBs

### ISSUE THREAD

**Issue by serapath** [serapath/gofree#2]
## `@todo`
* [x] Select open source tools to work with PCBs (e.g. KiCad). **KiCad was selected and will be used**
* [ ] [`gofree#11` single switch PCBs](https://github.com/serapath/gofree/issues/11)
* [ ] [`gofree#10` rigid flex PCB](https://github.com/serapath/gofree/issues/10)

---
* [KiCAD Software](https://www.kicad-pcb.org/)
* [KiCAD plugin](https://github.com/easyw/RF-tools-KiCAD)
* [KiCAD for flexpcb](https://www.youtube.com/watch?v=NIyFj2FNNf8)

**inspiration**
* https://pbs.twimg.com/media/EHcwJSKU4AAILbo.jpg
* https://deskthority.net/viewtopic.php?f=7&t=11420&start=
* https://imgur.com/r/MechanicalKeyboards/PBKDMJl

**Comment by Gondolindrim** [comment]
Since we are going with the open-source approach, I think that KiCad and OpenJSCad are our best options, specially since the nightly builds of KiCad are showing really promising features for the new versions.

**Comment by Gondolindrim** [comment]
Also I think we should develop more on the Flex PCB issue. I don't know how it is designed nor manufactured, so I will search and study more
