### ISSUE TITLE
3D case model

### ISSUE THREAD

**Issue by serapath** [serapath/gofree#3]
## `@todo`
* [ ] use [`openjscad`](https://openjscad.org) to model the 3D case for the device
  * OpenJSCad will be used for modelling
* [ ] add notches or screw holes to keep single switch PCBs fixed in their slots
  * according to [`gofree#4` keyboard layout](https://github.com/serapath/gofree/issues/4)
* [ ] [`gofree#13` measure hand size](https://github.com/serapath/gofree/issues/13)
* [ ] add attachement points to the shape so it can stick to the hands heel or the gloves inner side of your hand and so that fingers can reach trackball and as many keys as possible
    * [`gofree#9` attach device to hand (e.g. glove)](https://github.com/serapath/gofree/issues/9)
    * https://imgur.com/a/wb8zUnt

---
**goal:** don't stick to the examples, but make it as minimal and lightweight as possible
* picture (plasticine) https://www.instagram.com/p/Bru9IHChpz1/
* video (plasticine) https://www.instagram.com/p/Bru7G-Rh46v/
* more inspiration https://www.pinterest.de/serapath/prisonbreak/

**progress so far (3D modelling with openjscad)**
* https://www.youtube.com/playlist?list=PLNxENndziy1R-nHRc6rbz4TRRPldppAM8
* https://github.com/kaosat-dev/gofree/tree/master/cad

---
### further inspiration:
**moonrim**
* https://moonrim.io/ko/post/m4b1
* https://www.youtube.com/watch?v=73s5U4QIP4k&feature=youtu.be
* https://moonrim.io/en
* https://twitter.com/MoonrimProject

**inspiration (slots for keys)**
* https://i.imgur.com/kGc3seK.jpg
* [example single switch pcb](https://cdn.shopify.com/s/files/1/2563/1456/products/2_615b54dc-23bf-4e69-98c8-fa5fcead82a8_480x480.jpg?v=1576869869)
* [exmaple print with slots for PCBs](https://www.reddit.com/r/MechanicalKeyboards/comments/ad2xvo/ameoba_is_end_game/)

**inspiration (form factor)**
* https://imgur.com/r/MechanicalKeyboards/PBKDMJl
* https://imgur.com/a/pcpKkWQ
* https://i.imgur.com/vslk2fX.jpg
* https://imgur.com/a/ST43cKq
* https://imgur.com/a/SXGBnDG
* [logictech trackball mouse](https://www.google.com/search?q=trackball+mx+ergo&tbm=isch&ved=2ahUKEwjDsOWLicnoAhX9ADQIHSX4CNcQ2-cCegQIABAA&oq=trackball+mx+ergo&gs_lcp=CgNpbWcQAzIGCAAQBRAeMgYIABAIEB4yBggAEAgQHjoECAAQQzoCCAA6BggAEAoQGFCLH1i5KGDOKWgAcAB4AIABR4gB7AOSAQE4mAEAoAEBqgELZ3dzLXdpei1pbWc&sclient=img&ei=VYCFXoOyIf2B0PEPpfCjuA0&bih=943&biw=1905&hl=en-GB)
* sherbet game pad http://www.billiam.org/2019/05/29/sherbet-an-ergonomic-keypad
* lime40 https://www.pixiv.net/fanbox/creator/30358579
* lime40 https://twitter.com/eucalyn_/status/1186541310880055297
* https://www.reddit.com/r/MechanicalKeyboards/comments/9tyk5r/idea_for_an_ergonomic_thumb_cluster_has_something/

**Comment by serapath** [comment]
**how to work on this:**
1. git clone https://github.com/jscad/OpenJSCAD.org.git
2. cd OpenJSCAD.org
3. git checkout -b V2 origin/V2
4. git checkout 5db295d
5. npm install
6. npm run web
7. Open my browser and go to http://192.168.1.6:8081/ (which is what the terminal told me as the IP/PORT
