### ISSUE TITLE
keyboard layout

### ISSUE THREAD

**Issue by serapath** [serapath/gofree#4]
## `@todo`
* [ ] research the maximum amount of mechanical keys which would fit onto the device
* [ ] research best keyboard layout
* [ ] take https://matias.ca/halfkeyboard/ into account
* [ ] [`gofree#13` measure hand size](https://github.com/serapath/gofree/issues/13)

---
**goal:**
1. One requirement is, that the "thumb area" on both "keyboard gloves" is reserved for trackballs.
2. Otherwise, the 4 remaining fingers on each "keyboard glove" should be able to deal with or reach 36 keys at minimum but rather ~40 keys
not every row needs the full amount, but a 6 x 7 key grid would be the target

I tried to reach each of the key surfaces with my fingers male medium sized hand (according to https://www.healthline.com/health/average-hand-size#takeaway) and succeeded. Maybe a properly curved and more ergonomic layout could improve this further.

I was drawing a grid with the size for mini choc switches, but instead of `13.5` i did `14` and instead of `14.5` i did `15`, so between each key there would be `1mm` wiggle room.

The amound of keys is:
* 6x4 = 24 keys on the bottom
* 6x6 = 36 keys on the vertical surface
* 1x6 = 6 on top of the vertical surface

That's a maximum of a total of 66 keys per hand
Given two such gloves for both hands means a possible total of 132 keys which is way more than needed, so it is totally possible to:

1. either leave out a few keys
2. or use the larger normal switches instead of the mini ones, because they don't add a lot
3. or come up with a smart key layout so that someone could actually totally be fine with only a single "keyboard glove" instead of one for each hand

![keyboard layout](https://i.imgur.com/CGuogY3.jpg)

**consider further keys using special techniques**
* e.g. clickable plates row mounted between palm and bended fingers
* https://www.pinterest.de/pin/539798705337761080/
* https://www.pinterest.de/pin/AYkYKHdm1C2X3YVzwANI6nnCA3P1e4X5oiwf9pH-VUvzMX9JBNcoD30/
* https://www.pinterest.de/pin/539798705337761149/
* https://www.pinterest.de/pin/539798705337761434/
* https://www.pinterest.de/pin/539798705337762350/
