### ISSUE TITLE
device software

### ISSUE THREAD

**Issue by serapath** [serapath/gofree#7]
## `@todo`
* [ ] plan for drivers to work cross platform (win, macOSx, iOS, linux, android, ... smart-TV's?)
* [ ] research existing open source keyboard software to see if any can be re-used
  * https://qmk.fm/ ?
  * https://github.com/cswetenham/qmk_firmware/tree/feature/add-minidox-catalyst/keyboards/minidox/keymaps/catalyst
  * https://tessel.io/ supports `RUST`
    * device software in rust https://docs.rs/pc-keyboard/0.5.0/pc_keyboard/
    * https://github.com/thejpster/pc-keyboard
    * https://github.com/ah-/anne-key
* [ ] research and choose or program driver software
* [ ] support programmable keyboard layouts
* [ ] support to update and store current layout on the device itself
* [ ] support bluetooth 5 connectivity
* [ ] support USB-C recharging
* [ ] support trackball
* [ ] support software update from within web browsers (via web bluetooth or usb)
* [ ] make fully programmable over USB-C or Bluetooth 5 from a web browser interface

---
